import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const desk = readFileSync(new URL("../desk.js", import.meta.url), "utf8");
const batch = readFileSync(new URL("../material-batch.js", import.meta.url), "utf8");
const view = readFileSync(new URL("../desk-material-batch.js", import.meta.url), "utf8");
assert.match(desk, /installMaterialBatch/);
assert.match(batch, /\/api\/library\/materials\/preview/);
assert.match(batch, /token !== generation/);
assert.match(view, /estimated_storage_bytes/);
assert.match(view, /preview\.page_count/);
assert.match(batch, /URL\.revokeObjectURL\(url\)/);
assert.match(batch, /video\.onerror = null/);
const tools = readFileSync(new URL("../desk-tools.js", import.meta.url), "utf8");
assert.match(tools, /study-activity-grid/);
assert.match(tools, /resume-study/);
assert.match(tools, /delete_all_study_data/);
assert.match(desk, /initialized\.plan\?\.paused/);
console.log("Preflight has stale-file guards and study controls preserve paused/clear-data semantics");
