import assert from "node:assert/strict";
import { createSidepanelHarness, videoContext } from "./sidepanel_test_harness.mjs";
const health = {service:"learnnote",app_version:"0.2.7",backend_version:"0.2.7",protocol_version:1,llm_model_configured:false,default_llm_model:"mimo-v2.5"};
const context = videoContext();
const h = await createSidepanelHarness({contexts:[context,context],health});
assert.equal(h.elements.get("#sendButton").disabled,true);
assert.equal(h.elements.get("#configureModelButton").hidden,false);
assert.equal(await h.api.sendToClient(),false);
assert(!h.sentMessages.some(m=>m.type==="start-current-task"));
h.api.setProcessingMode("quick");
assert.equal(h.elements.get("#sendButton").disabled,false);
assert.equal(h.elements.get("#modelReadiness").hidden,true);
assert.equal(await h.api.sendToClient(),true);
assert.equal(h.sentMessages.find(m=>m.type==="start-current-task").options.content_mode,"subtitles");
const ready = await createSidepanelHarness({contexts:[context],health:{...health,llm_model_configured:true}});
assert.match(ready.elements.get("#modelReadinessText").textContent,/mimo-v2.5/);
assert.equal(ready.elements.get("#sendButton").disabled,false);
console.log("Missing model stops AI work before extraction; captions remain available; selected model is visible");
const textOnly = await createSidepanelHarness({contexts:[context],health:{...health,llm_model_configured:true,default_llm_supports_vision:false}});
textOnly.api.setProcessingMode("deep");
assert.equal(textOnly.elements.get("#sendButton").disabled,true);
assert.match(textOnly.elements.get("#modelReadinessText").textContent,/不支持图片/);
assert.equal(await textOnly.api.sendToClient(),false);
assert(!textOnly.sentMessages.some(m=>m.type==="start-current-task"));
textOnly.api.setProcessingMode("study");
assert.equal(textOnly.elements.get("#sendButton").disabled,false);
console.log("Known text-only models block visual work before capture while text notes remain available");
