import { contentScriptSource } from "./content_script_loader.mjs";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import vm from "node:vm";
import {createSidepanelHarness,videoContext} from "./sidepanel_test_harness.mjs";
const code=await contentScriptSource();let ld=[];
const ctx={URL,location:{href:"https://www.youtube.com/watch?v=abcdefghijk"},document:{querySelectorAll:s=>s==='script[type="application/ld+json"]'?ld:[]},chrome:{runtime:{onMessage:{addListener(){}}}},window:{}};
vm.createContext(ctx);vm.runInContext(code+"\nglobalThis.readChapters=collectChapterEvidence;",ctx);
const video={duration:600,textTracks:[{kind:"chapters",cues:[{startTime:0,endTime:120,text:"Original chapter 章节"},{startTime:120,endTime:600,text:"Second chapter"}]},{kind:"subtitles",cues:[{startTime:0,endTime:600,text:"Not chapter evidence"}]}]};
let chapters=ctx.readChapters(video);assert.equal(chapters.length,2);assert.equal(chapters[0].title,"Original chapter 章节");
assert.equal(ctx.readChapters({duration:600,textTracks:[{kind:"chapters",get cues(){throw Error("Cross-origin cue access denied");}}]}).length,0);
ld=[{textContent:JSON.stringify({"@type":"VideoObject",url:ctx.location.href,hasPart:[{"@type":"Clip",startOffset:0,endOffset:60,name:"Intro"},{"@type":"Clip",startOffset:60,endOffset:90,name:"Definition"}]})},{textContent:JSON.stringify({"@type":"VideoObject",url:"https://www.youtube.com/watch?v=other",hasPart:[{"@type":"Clip",startOffset:0,endOffset:600,name:"Wrong video"}]})}];
chapters=ctx.readChapters({duration:600,textTracks:[]});assert.equal(chapters.length,2);assert.equal(chapters[1].provenance,"structured_video_clip");
const h=await createSidepanelHarness({contexts:[videoContext()]});h.elements.set("#learningRangeMode",{value:"current5"});h.elements.set("#learningRangeStart",{value:""});h.elements.set("#learningRangeEnd",{value:""});
const context=videoContext();context.page.active_video.current_time=570;context.page.active_video.duration=600;context.page.chapters=[{start:500,end:600,title:"End chapter"}];
assert.deepEqual(JSON.parse(JSON.stringify(h.api.learningRange(context))),{start:570,end:600});
h.elements.get("#learningRangeMode").value="chapter";assert.deepEqual(JSON.parse(JSON.stringify(h.api.learningRange(context))),{start:500,end:600});context.page.chapters=[];assert.throws(()=>h.api.learningRange(context),/章节/);
h.elements.get("#learningRangeMode").value="custom";h.elements.get("#learningRangeStart").value="12";h.elements.get("#learningRangeEnd").value="30";assert.deepEqual(JSON.parse(JSON.stringify(h.api.learningRange(context))),{start:12,end:30});
const identity=h.api.buildSourceIdentity(context),first=h.api.handoffId(identity,{start:0,end:60});assert.equal(h.api.handoffId(identity,{start:0,end:60}),first);assert.notEqual(h.api.handoffId(identity,{start:60,end:120}),first);
console.log("Source-backed chapters, bounded position presets and range-scoped handoffs pass");
